import{S as L,a as S,i as w}from"./assets/vendor-90c85f31.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function c(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=c(t);fetch(t.href,r)}})();const q="/goit-js-hw-12/assets/error-80ee8afe.svg",E="https://pixabay.com/api/",P="41804111-1b8e3eb7a4ad0f0fdba68370e";let m;const o={key:P,q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40},k=new L(".gallery a",{overlayOpacity:.8,captionsData:"alt",captionDelay:250}),p=document.querySelector(".form"),u=document.querySelector(".search-input"),y=document.querySelector(".gallery"),f=document.querySelector(".loader"),i=document.querySelector(".load-more-btn");p.addEventListener("submit",$);i.addEventListener("click",O);async function $(e){if(e.preventDefault(),!u.value.trim()){l("Please, fill out the search field");return}y.innerHTML="",o.q=u.value.trim(),o.page=1,d(i),g()}function O(){o.page+=1,g()}async function g(){h(f);try{const e=await S.get(`${E}`,{params:o});A(e.data)}catch(e){l(e.message)}d(f)}function A(e){if(e.total===0){l("Sorry, there are no images matching your search query. Please try again!"),u.value="";return}m=e.totalHits;const s=e.hits.map(({largeImageURL:c,webformatURL:a,tags:t,likes:r,views:n,comments:b,downloads:v})=>`
        <li class="gallery-item">
          <a href="${c}">
            <img class="gallery-image" src="${a}" alt="${t}">
            <div class="img-desc">
              <span><b>Likes:</b> <br/>${r}</span>
              <span><b>Views:</b> <br/>${n}</span>
              <span><b>Comments:</b> <br/>${b}</span>
              <span><b>Downloads:</b> <br/>${v}</span>
            </div>
          </a>
        </li>
                  `).join("");y.insertAdjacentHTML("beforeend",s),M(),B(),k.refresh(),p.reset()}function M(){Math.ceil(m/o.per_page)===o.page?(l("We're sorry, but you've reached the end of search results."),d(i)):h(i)}function B(){if(o.page>1){const e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*2,left:0,behavior:"smooth"})}}function l(e){w.show({position:"topRight",iconUrl:q,messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0,closeOnEscape:!0,message:e})}function h(e){e.style.display="inline-block"}function d(e){e.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
